#!/bin/sh
# Run from OPENFOAM applications/ directory only
cd "${0%/*}" || exit
wmake -check-dir "$WM_PROJECT_DIR/applications" 2>/dev/null || {
    echo "Error (${0##*/}) : not located in \$WM_PROJECT_DIR/applications"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
}
if [ -f "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments ]
then  . "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments || \
    echo "Argument parse error"
else
    echo "Error (${0##*/}) : WM_PROJECT_DIR appears to be incorrect"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
fi

echo ========================================
echo Compile OpenFOAM applications
echo ========================================

#------------------------------------------------------------------------------

# Utilities
# wmake -all $targetType utilities
wmake -all $targetType utilities/finiteArea
wmake -all $targetType utilities/doc
wmake -all $targetType utilities/mesh/advanced
wmake -all $targetType utilities/mesh/conversion
wmake -all $targetType utilities/mesh/doc
wmake -all $targetType utilities/mesh/generation/PDRblockMesh
wmake -all $targetType utilities/mesh/generation/blockMesh
# wmake -all $targetType utilities/mesh/generation/extrude
wmake -all $targetType utilities/mesh/generation/extrude2DMesh
wmake -all $targetType utilities/mesh/generation/foamyMesh
wmake -all $targetType utilities/mesh/generation/snappyHexMesh
wmake -all $targetType utilities/mesh/manipulation
wmake -all $targetType utilities/miscellaneous
wmake -all $targetType utilities/preProcessing
wmake -all $targetType utilities/postProcessing
wmake -all $targetType utilities/parallelProcessing
wmake -all $targetType utilities/surface
wmake -all $targetType utilities/thermophysical

# Solvers
# wmake -all $targetType solvers
wmake $targetType solvers/basic/laplacianFoam
wmake $targetType solvers/basic/potentialFoam
wmake $targetType solvers/compressible/rhoPimpleFoam
wmake $targetType solvers/incompressible/icoFoam
wmake $targetType solvers/incompressible/pisoFoam
wmake $targetType solvers/incompressible/simpleFoam
wmake $targetType solvers/incompressible/simpleFoam/SRFSimpleFoam
wmake $targetType solvers/incompressible/pimpleFoam

# Extra tools (optional)
wmake -all $targetType tools

#------------------------------------------------------------------------------

echo ========================================
echo Done OpenFOAM applications
echo ========================================

#------------------------------------------------------------------------------
