#!/bin/sh
# Run from OPENFOAM applications/ directory only
cd "${0%/*}" || exit
wmake -check-dir "$WM_PROJECT_DIR/applications" 2>/dev/null || {
    echo "Error (${0##*/}) : not located in \$WM_PROJECT_DIR/applications"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
}
if [ -f "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments ]
then  . "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments || \
    echo "Argument parse error"
else
    echo "Error (${0##*/}) : WM_PROJECT_DIR appears to be incorrect"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
fi

echo ========================================
echo Compile OpenFOAM applications
echo ========================================

#------------------------------------------------------------------------------

# wmake -all $targetType utilities
wmake -all $targetType utilities/finiteArea
wmake -all $targetType utilities/doc

wmake -all $targetType utilities/mesh/advanced
wmake -all $targetType utilities/mesh/conversion
wmake -all $targetType utilities/mesh/doc
wmake -all $targetType utilities/mesh/generation/PDRblockMesh
wmake -all $targetType utilities/mesh/generation/blockMesh
# wmake -all $targetType utilities/mesh/generation/extrude # error
wmake -all $targetType utilities/mesh/generation/extrude2DMesh
wmake -all $targetType utilities/mesh/generation/foamyMesh
wmake -all $targetType utilities/mesh/generation/snappyHexMesh
wmake -all $targetType utilities/mesh/manipulation

wmake -all $targetType utilities/miscellaneous
wmake -all $targetType utilities/preProcessing
wmake -all $targetType utilities/postProcessing
wmake -all $targetType utilities/parallelProcessing

wmake -all $targetType utilities/surface/surfaceAdd
wmake -all $targetType utilities/surface/surfaceBooleanFeatures
wmake -all $targetType utilities/surface/surfaceCheck
wmake -all $targetType utilities/surface/surfaceClean
wmake -all $targetType utilities/surface/surfaceCoarsen
wmake -all $targetType utilities/surface/surfaceConvert
wmake -all $targetType utilities/surface/surfaceFeatureConvert
wmake -all $targetType utilities/surface/surfaceFeatureExtract
wmake -all $targetType utilities/surface/surfaceFind
wmake -all $targetType utilities/surface/surfaceHookUp
wmake -all $targetType utilities/surface/surfaceInertia
wmake -all $targetType utilities/surface/surfaceInflate
wmake -all $targetType utilities/surface/surfaceLambdaMuSmooth
wmake -all $targetType utilities/surface/surfaceMeshConvert
wmake -all $targetType utilities/surface/surfaceMeshExport
# wmake -all $targetType utilities/surface/surfaceMeshExtract #error
wmake -all $targetType utilities/surface/surfaceMeshImport
wmake -all $targetType utilities/surface/surfaceMeshInfo
wmake -all $targetType utilities/surface/surfaceOrient
wmake -all $targetType utilities/surface/surfacePatch
wmake -all $targetType utilities/surface/surfacePointMerge
wmake -all $targetType utilities/surface/surfaceRedistributePar
wmake -all $targetType utilities/surface/surfaceRefineRedGreen
wmake -all $targetType utilities/surface/surfaceSplitByPatch
wmake -all $targetType utilities/surface/surfaceSplitByTopology
wmake -all $targetType utilities/surface/surfaceSplitNonManifolds
wmake -all $targetType utilities/surface/surfaceSubset
wmake -all $targetType utilities/surface/surfaceToPatch
wmake -all $targetType utilities/surface/surfaceTransformPoints

wmake -all $targetType utilities/thermophysical

# Solvers
wmake -all $targetType solvers

# Extra tools (optional)
wmake -all $targetType tools

#------------------------------------------------------------------------------

echo ========================================
echo Done OpenFOAM applications
echo ========================================

#------------------------------------------------------------------------------
