#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
targetType=libo                                     # Preferred library type
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments $*

#------------------------------------------------------------------------------

if [ -f /usr/include/FlexLexer.h ] && [ -d lnInclude ] && [ ! -f lnInclude/FlexLexer.h ]
then
    echo "Copying FlexLexer.h into ${PWD##*/}/lnInclude for cross-compilation"
    cp /usr/include/FlexLexer.h lnInclude/FlexLexer.h
fi

unset COMP_FLAGS LINK_FLAGS

# Make object (non-shared by default)
# Never want/need openmp, especially for static objects
wmake -no-openmp $targetType

#------------------------------------------------------------------------------
