#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory

wclean thermalTurbulenceModels
wclean incompressible
wcleanLnIncludeAll

#------------------------------------------------------------------------------
